import { Providers } from "@app/providers";
import Navbar from "@components/Navbar";
import { getSession } from "@auth";

import { Rubik } from "next/font/google";

import "@styles/fonts.css";
import "@styles/globals.css";

import { classNames } from "@utils/index";

import Constants from "@constants/index";

export const metadata = {
  title: {
    default: "Home",
    template: `%s | ${Constants.APP_NAME}`,
  },
  description: "Generated by Next.js",
};

const rubik = Rubik({
  subsets: ["latin"],
  display: "swap",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();
  return (
    <html
      className={classNames(rubik.className, "dark")}
      style={{ colorScheme: "dark" }}
      lang="en"
    >
      <body>
        <Providers>
          <div className="box-border max-w-full">
            <Navbar session={session} />
            <main className="mx-auto mt-20 max-w-7xl sm:px-6 lg:px-8">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
